### ISSUE TITLE
root-level oneOf not handled proper - validates against all types

### ISSUE THREAD

**Issue by justinfx** [santhosh-tekuri/jsonschema#195]
I just wanted to start by saying after trying a few different jsonschema validation libraries, yours has been the closest to handling my particular schema correctly.

Given the following jsonschema:
https://github.com/argoproj/argo-events/blob/master/api/jsonschema/schema.json

It uses a top level object that is a `oneOf` of 3 possible types:

```
...
  "oneOf": [
    {
      "$ref": "#/definitions/io.argoproj.events.v1alpha1.EventBus"
    },
    {
      "$ref": "#/definitions/io.argoproj.events.v1alpha1.EventSource"
    },
    {
      "$ref": "#/definitions/io.argoproj.events.v1alpha1.Sensor"
    }
  ],
  "type": "object"
}
```

And then the following yaml input:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: name
spec:
  BADFIELD: true
  nats:
    example:
      url: host:1234
      jsonBody: true
      subject: a.b.c
      tls:
        # should be bool
        insecureSkipVerify: [] 
```

I get the following output:

```
schema schemas/argo-events.json: ok

instance eventsource.yaml: failed
jsonschema validation failed with 'file:///schemas/argo-events.json#'
- at '': oneOf failed, none matched
  - at '/kind': value must be 'EventBus'
  - at '/spec/nats/example/tls/insecureSkipVerify': got array, want boolean
  - at '': validation failed
    - at '/kind': value must be 'Sensor'
    - at '/spec': missing properties 'dependencies', 'triggers'
```

The validation about `insecureSkipVerify` is spot on. However given that the top level `oneOf` says it could be one of 3 different types, it seems to be validating against all 3 instead of just the `EventSource` kind. 

Bonus points, it doesn't seem to catch undefined fields, like "BADFIELD"
