### ISSUE TITLE
Sum types validation error (anyOf, oneOf)

### ISSUE THREAD

**Issue by ndopj** [santhosh-tekuri/jsonschema#210]
Suppose a scenario where user is modelling JSON schema to achieve a polymorphism or union functionality
```yaml
$schema: https://json-schema.org/draft/2020-12/schema
$id: schemas/sum.yml
type: object
oneOf:
  - $ref: schemas/A.yml
  - $ref: schemas/B.yml
```
```yaml
$schema: https://json-schema.org/draft/2020-12/schema
$id: schemas/A.yml
type: object
properties:
  category:
    type: string
    const: categoryA
required:
  - category
```
```yaml
$schema: https://json-schema.org/draft/2020-12/schema
$id: schemas/B.yml
type: object
properties:
  category:
    type: string
    const: categoryB
  context:
    type: string
    enum:
     - ctx1
     - ctx2
required:
  - category
  - context
```

This library will correctly validate incoming example data and mark them as invalid (*note that value `ctx3` is not enumerated in definitions above*):
```json
{
  "category": "categoryB",
  "context": "ctx3"
}
```

However, the returned error when calling `err.Error()` (*obtained from `Validate()` function*) will point to the first schema - which is not related to incoming data in any way. If we change `err.Error()` to `fmt.Sprintf("%#v", err)` full error message can be obtain which will state that incoming data failed to validate against all of the `oneOf` subschemas. This is expected and is correct behaviour.

On the other hand, I think it would be really meaningful if there was optionality or default behaviour for `err.Error()` to return error for the subschema of `oneOf` keyword which was the one closest to be validated (*or the one that validated largest part of the incoming data*). So in the example I've outlined above, only errors for schema `schemas/B.yml` would be returned.

This behaviour would greatly help users in resolving validation errors unlike current solution which might return errors that are not expected by the users in the given context of the schema.

Possible other issues where this would be helpful:
- https://github.com/santhosh-tekuri/jsonschema/issues/205
- https://github.com/santhosh-tekuri/jsonschema/issues/195
- https://github.com/santhosh-tekuri/jsonschema/issues/105
- https://github.com/santhosh-tekuri/jsonschema/issues/87
