### ISSUE TITLE
Error output not stable

### ISSUE THREAD

**Issue by lzap** [santhosh-tekuri/jsonschema#213]
Hello,

haing this YAML input (turned into JSON, small detail):

```yaml
name: "Blueprint example: accounts"
accounts:
  users:
    - name: "-names-starting-with-dash"
    - name: >-
        all-names-longer-than-256-characters--------------------------------------
        --------------------------------------------------------------------------
        --------------------------------------------------------------------------
        --------------------------------------------------------------------------
    - name: "names-with-diakritics-žluťoučký-kůň"
    - name: "names with spaces"
    - name: "uid-0"
      uid: 0
  groups:
    - name: "-the-same-for-groups"
```

And a schema: https://github.com/osbuild/blueprint-schema/blob/main/blueprint-schema.json

The validation generates an output that has random order, one option:

```
validation failed: jsonschema validation failed with 'blueprint-schema.json'
- at '/accounts': oneOf failed, none matched
  - at '/accounts': validation failed
    - at '/accounts/groups': oneOf failed, none matched
      - at '/accounts/groups/0/name': '-the-same-for-groups' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
      - at '/accounts/groups': got array, want null
    - at '/accounts/users': oneOf failed, none matched
      - at '/accounts/users': validation failed
        - at '/accounts/users/0/name': '-names-starting-with-dash' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/1': validation failed
          - at '/accounts/users/1/name': maxLength: got 299, want 256
          - at '/accounts/users/1/name': 'all-names-longer-than-256-characters-------------------------------------- -------------------------------------------------------------------------- -------------------------------------------------------------------------- --------------------------------------------------------------------------' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/2/name': 'names-with-diakritics-žluťoučký-kůň' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/3/name': 'names with spaces' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/4/uid': minimum: got 0, want 1
      - at '/accounts/users': got array, want null
  - at '/accounts': got object, want null
```

And option two:

```
validation failed: jsonschema validation failed with 'blueprint-schema.json'
- at '/accounts': oneOf failed, none matched
  - at '/accounts': validation failed
    - at '/accounts/users': oneOf failed, none matched
      - at '/accounts/users': validation failed
        - at '/accounts/users/0/name': '-names-starting-with-dash' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/1': validation failed
          - at '/accounts/users/1/name': maxLength: got 299, want 256
          - at '/accounts/users/1/name': 'all-names-longer-than-256-characters-------------------------------------- -------------------------------------------------------------------------- -------------------------------------------------------------------------- --------------------------------------------------------------------------' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/2/name': 'names-with-diakritics-žluťoučký-kůň' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/3/name': 'names with spaces' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
        - at '/accounts/users/4/uid': minimum: got 0, want 1
      - at '/accounts/users': got array, want null
    - at '/accounts/groups': oneOf failed, none matched
      - at '/accounts/groups/0/name': '-the-same-for-groups' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
      - at '/accounts/groups': got array, want null
  - at '/accounts': got object, want null
```

In `cmp` package language that is:

```
--- FAIL: TestFix (0.00s)
    --- FAIL: TestFix/Valid/fixtures/accounts-invalid-names.in.yaml (0.01s)
        validate_test.go:154: validity mismatch (-want +got):
              (
                """
                validation failed: jsonschema validation failed with 'blueprint-schema.json'
                - at '/accounts': oneOf failed, none matched
                  - at '/accounts': validation failed
            +       - at '/accounts/groups': oneOf failed, none matched
            +         - at '/accounts/groups/0/name': '-the-same-for-groups' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
            +         - at '/accounts/groups': got array, want null
                    - at '/accounts/users': oneOf failed, none matched
                      - at '/accounts/users': validation failed
                ... // 6 identical lines
                        - at '/accounts/users/4/uid': minimum: got 0, want 1
                      - at '/accounts/users': got array, want null
            -       - at '/accounts/groups': oneOf failed, none matched
            -         - at '/accounts/groups/0/name': '-the-same-for-groups' does not match pattern '^[a-zA-Z0-9_.][a-zA-Z0-9_.$-]*$'
            -         - at '/accounts/groups': got array, want null
                  - at '/accounts': got object, want null
                """
              )
```

Is there any chance to sort/stabilize the order in this case? Or do you have a recommendation for me how to do validation test comparison? Thanks!
